#!/usr/bin/env bash

# script to dig subdomain records for the domain specified
# shellcheck disable=SC2027
# shellcheck disable=SC2086

function get_a_records() {
    if [[ -n "$2" ]]; then
        response=$(dig "$2.$1" +short | head -n 1)
        if [[ -n "$response" ]]; then
            echo "The subdomain $2 is an A record and points to $response"
        else
            echo "No records found for the subdomain $2"
        fi
    else
        subdomains=(www lb-01 web-01 web-02)
        for sub_d in "${subdomains[@]}"; do
            response=$(dig "$sub_d.$1" +short | head -n 1)
            if [[ -n "$response" ]]; then
                echo "The subdomain $sub_d is an A record and points to $response"
            else
                echo "No records found for the subdomain $sub_d"
            fi
        done
    fi
}

get_a_records "$1" "$2"
