#!/bin/bash

get_record_info() {
    local domain=$1
    local subdomain=$2
    local record_info=$(dig $subdomain.$domain | awk '/ANSWER SECTION:/{getline; print}')
    echo "The subdomain $subdomain is a $record_info record and points to $(echo $record_info | awk '{print $NF}')"
}

main() {
    local domain=$1
    local subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -z "$2" ]; then
        for subdomain in "${subdomains[@]}"; do
            get_record_info $domain $subdomain
        done
    else
        get_record_info $domain $2
    fi
}

main "$@"
