#!/usr/bin/env bash
# The installed server listens to port 80 (HTTP) for connection

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
