#!/usr/bin/env bash
# Write a Bash script that:

file=/var/run/myscript.pid
trap 'echo Y U no love me?!' SIGINT
trap 'rm -f $file; exit' SIGQUIT
trap 'echo I hate the kill command; rm -f $file; exit' SIGTERM
echo $$ > $file
while true; do
    echo "To infinity and beyond"
    sleep 1
done
