#!/usr/bin/env bash
# Write a Bash script that displays to infinity and beyond indefinitely.
# Requirements:
# + iter    tion sleep 2

while true; do
    echo "To infinity and beyond"
    sleep 2
done