#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

itr=1

while [ "$itr" -le 20 ]
do
    echo $itr
    case $itr in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((itr += 1))
done

exit 0
